fix font
Hoa0304/practice-html-css pull request #25
Opened 2023-10-15 12:11 UTC by Hoa0304

2023-10-17 06:01 UTC, PhamNhuQuocBao requested changes

2023-10-17 06:01 UTC, PhamNhuQuocBao commented on src/stylesheets/abstracts/_variable.scss
>  $color_initial_header:rgba(255, 255, 255, 0.50);
comment.

2023-10-17 06:01 UTC, PhamNhuQuocBao commented
I don't accept that you `set the font` for each element, instead `set the Montserrat font` as the main font for your entire website.

2023-10-20 08:59 UTC, Hoa0304 commented on src/stylesheets/abstracts/_variable.scss
>  $color_initial_header:rgba(255, 255, 255, 0.50);
set the font is here : https://github.com/Hoa0304/practice-html-css/pull/28/commits/3b8617e9d9c9e54914ff23fea7231623fecda1e8

2023-10-21 09:34 UTC, closed without merging